<?php
$pageTitle = 'FAQ Sourcée | Sciences, Vivant et Méthode | Flux Info';
$pageDesc = 'Questions fréquentes et réponses sourcées sur le cosmos, l’atmosphère, les sols, les océans, le vivant et la méthode éditoriale de Flux Info.';
$sections = [
'Cosmos et Origines' => [
 ['q'=>'Sommes-nous vraiment faits de poussière d’étoiles ?','level'=>'Fait Établi','a'=>'En grande partie, oui, mais la formule demande une nuance. L’hydrogène, l’hélium et une petite quantité de lithium proviennent surtout de la nucléosynthèse primordiale. Le carbone, l’oxygène, le fer et de nombreux autres éléments ont ensuite été produits ou transformés dans des étoiles et lors de leur évolution.','src'=>[['NASA - Star Stuff','https://starchild.gsfc.nasa.gov/docs/StarChild/questions/question57.html']]],
 ['q'=>'Pourquoi le fer marque-t-il une limite dans la fusion stellaire ?','level'=>'Fait Établi','a'=>'Jusqu’au groupe du fer, certaines réactions de fusion peuvent libérer de l’énergie dans les étoiles massives. Fusionner des noyaux autour du fer ne fournit plus cette même source d’énergie. Lorsqu’un cœur massif dominé par le fer ne peut plus être soutenu, il peut s’effondrer et conduire à une supernova.','src'=>[['NASA - Star Stuff','https://starchild.gsfc.nasa.gov/docs/StarChild/questions/question57.html']]],
 ['q'=>'Qu’est-ce que la nucléosynthèse stellaire ?','level'=>'Fait Établi','a'=>'C’est l’ensemble des processus nucléaires qui produisent de nouveaux noyaux atomiques dans les étoiles. Il ne faut pas en déduire que tous les éléments lourds ont une origine unique : plusieurs mécanismes interviennent, notamment au cours de l’évolution stellaire et d’événements explosifs.','src'=>[['NASA - Star Stuff','https://starchild.gsfc.nasa.gov/docs/StarChild/questions/question57.html']]],
],
'Les Souffles du Ciel' => [
 ['q'=>'L’atmosphère est-elle vraiment aussi fine qu’une pelure de pomme ?','level'=>'Métaphore Pédagogique','a'=>'La comparaison sert à faire sentir l’extrême minceur de la couche atmosphérique par rapport au rayon terrestre. La troposphère, où se produit l’essentiel de la météo, s’étend typiquement sur environ 8 à 15 km selon la latitude. L’atmosphère complète s’étend bien plus haut.','src'=>[['NASA - Atmospheric Layers','https://www.nasa.gov/image-article/earths-atmospheric-layers-3/']]],
 ['q'=>'Des micro-organismes peuvent-ils vivre dans les nuages ?','level'=>'Fait Établi','a'=>'Des bactéries, champignons et autres particules biologiques sont observés dans l’atmosphère et les nuages. Certaines particules biologiques peuvent aussi favoriser la nucléation de glace. En revanche, dire que les bactéries "font la pluie" serait une simplification excessive : la formation des nuages et des précipitations dépend de nombreux processus physiques.','src'=>[['Nature Reviews Physics - Ice Nucleation','https://www.nature.com/articles/s42254-023-00570-7'],['Nature - Marine Biogenic Ice Nuclei','https://www.nature.com/articles/nature14986']]],
 ['q'=>'Qu’est-ce qu’une rivière atmosphérique ?','level'=>'Fait Établi','a'=>'Une rivière atmosphérique est un corridor relativement étroit de transport intense de vapeur d’eau dans l’atmosphère. Ces structures peuvent acheminer de grandes quantités d’humidité et contribuer à des précipitations importantes lorsqu’elles rencontrent des conditions favorables.','src'=>[['NOAA - Atmospheric Rivers','https://www.nesdis.noaa.gov/about/k-12-education/atmosphere/what-atmospheric-river']]],
],
'Les Traces de la Terre' => [
 ['q'=>'Pourquoi dire que le sol est une archive ?','level'=>'Métaphore Pédagogique','a'=>'Le mot "archive" est une image. Un sol conserve toutefois des traces de son histoire : matière organique, structures, minéraux, pollens, carbone, communautés microbiennes et effets des usages passés. Un sol sain peut abriter une abondance considérable de micro-organismes.','src'=>[['USDA NRCS - Healthy Soils Are Full of Life','https://nrcspad.sc.egov.usda.gov/DistributionCenter/pdf.aspx?productID=1023']]],
 ['q'=>'Que nous apprend la Grande Migration du Serengeti ?','level'=>'Fait Établi','a'=>'Elle montre comment les déplacements d’immenses populations d’herbivores suivent les saisons, les pluies, la disponibilité et la qualité du fourrage, tout en modifiant à leur tour les relations écologiques. Ce n’est pas un mécanisme d’horlogerie : plusieurs facteurs interagissent et varient selon les périodes.','src'=>[['Scientific Reports - Serengeti Rainfall and Migration','https://www.nature.com/articles/s41598-022-22053-y'],['Nature - Mineral Nutrition and Seasonal Movements','https://www.nature.com/articles/345613a0']]],
 ['q'=>'Les arbres "communiquent-ils" par un Wood Wide Web ?','level'=>'Hypothèse Discutée','a'=>'Les champignons mycorhiziens forment des symbioses avec les racines et peuvent relier plusieurs plantes. Des transferts de ressources existent dans certains contextes. En revanche, les récits populaires décrivant des arbres qui s’envoient volontairement des ressources ou des messages d’alerte à grande échelle vont souvent plus loin que les preuves disponibles.','src'=>[['Nature Ecology & Evolution - Common Mycorrhizal Networks','https://www.nature.com/articles/s41559-023-01986-1'],['Nature - Mother Tree Debate','https://www.nature.com/articles/d41586-024-00893-0']]],
],
'Les Profondeurs de l’Océan' => [
 ['q'=>'Connaît-on mieux la Lune que les fonds marins ?','level'=>'Métaphore Pédagogique','a'=>'La formule est frappante mais difficile à comparer littéralement. Ce que l’on peut affirmer est que l’océan profond reste très peu observé directement. En avril 2026, 28,7 % du plancher océanique mondial avait été cartographié à haute résolution moderne, et moins de 0,001 % du plancher de l’océan profond avait été observé visuellement selon NOAA.','src'=>[['NOAA Ocean Exploration - How Much Has Been Explored?','https://oceanexplorer.noaa.gov/ocean-fact/explored/']]],
 ['q'=>'Quelle part de l’oxygène est produite par l’océan ?','level'=>'Ordre de Grandeur','a'=>'NOAA estime qu’environ la moitié de la production d’oxygène de la Terre provient de l’océan, principalement du plancton photosynthétique. Cette valeur est un ordre de grandeur : elle varie et une part importante de cet oxygène est aussi consommée par les organismes et processus marins.','src'=>[['NOAA - How Much Oxygen Comes from the Ocean?','https://oceanservice.noaa.gov/facts/ocean-oxygen.html']]],
],
'Humanité, Vivant et Conscience' => [
 ['q'=>'Pourquoi Flux Info parle-t-il de culture en plus de biologie ?','level'=>'Réflexion Philosophique','a'=>'Parce que Flux Info s’intéresse aussi aux flux d’information, de mémoire et de transmission qui structurent les sociétés humaines. Cela ne remplace pas la biologie : c’est un choix éditorial pour relier organisme, culture, techniques et institutions.','src'=>[]],
 ['q'=>'Le vivant "lutte-t-il" contre l’entropie ?','level'=>'Métaphore Pédagogique','a'=>'Dire que le vivant "lutte" contre l’entropie est une métaphore. Les organismes maintiennent localement des structures organisées grâce à des échanges continus de matière et d’énergie avec leur environnement. Cela ne contredit pas la deuxième loi de la thermodynamique appliquée au système plus large.','src'=>[]],
 ['q'=>'La conscience est-elle propre à l’humain ?','level'=>'Hypothèse Discutée','a'=>'La réponse dépend d’abord de la définition de la conscience et des critères retenus. La recherche étudie des formes de perception, cognition et expérience chez de nombreux animaux, mais Flux Info ne présente pas l’idée d’une conscience diffuse dans tout le vivant comme un fait établi. Les passages qui l’évoquent relèvent de la réflexion philosophique.','src'=>[]],
],
'Flux Info, Archipel et Méthode' => [
 ['q'=>'Qu’est-ce que Flux Info ?','level'=>'Définition','a'=>'Flux Info est un média pédagogique indépendant qui explique les flux de matière, d’énergie, d’information et de vivant reliant la Biosphère, les sociétés humaines et les technologies. Ses articles, cartes et expériences rendent visibles les interdépendances sans remplacer les publications scientifiques auxquelles ils renvoient.','src'=>[['À propos de Flux Info','apropos.php'],['Charte Éditoriale de Flux Info','politique-editoriale.php']]],
 ['q'=>'Qu’est-ce qu’Archipel dans Flux Info ?','level'=>'Choix Éditorial','a'=>'Océan, Ciel, Terre, Cosmos et Humanité sont les grands territoires d’exploration. Archipel est la couche relationnelle : il montre comment les phénomènes de ces territoires se rencontrent. Le site partenaire "Archipel de la Conscience" est un projet distinct de la Porte Archipel de Flux Info.','src'=>[]],
 ['q'=>'Pourquoi le design est-il sombre et contemplatif ?','level'=>'Choix Éditorial','a'=>'Le design cherche à ralentir la lecture et à donner une continuité visuelle entre abysses, atmosphère, cosmos et réseaux du vivant. Le Mode lecture offre une présentation plus sobre lorsqu’on souhaite privilégier le texte.','src'=>[]],
 ['q'=>'Les simulateurs sont-ils des modèles scientifiques prédictifs ?','level'=>'Métaphore Pédagogique','a'=>'Non. Ce sont des expériences interactives simplifiées destinées à rendre perceptible une relation entre quelques paramètres. Elles ne remplacent ni un modèle scientifique validé, ni une simulation de recherche, ni une prévision.','src'=>[]],
 ['q'=>'Comment Flux Info utilise-t-il les intelligences artificielles ?','level'=>'Méthode','a'=>'Des systèmes comme ChatGPT, Manus, Claude et Gemini ont été utilisés comme outils de dialogue, de structuration, de relecture, d’exploration ou de prototypage. Une réponse d’IA n’est pas considérée comme une source et la responsabilité éditoriale finale reste humaine.','src'=>[]],
 ['q'=>'D’où viennent les sources scientifiques ?','level'=>'Méthode','a'=>'Flux Info privilégie les organismes publics, rapports de référence, publications académiques et revues de synthèse. Les sources sont indiquées dans les articles et, lorsque cela est utile, au niveau de la réponse elle-même.','src'=>[]],
 ['q'=>'Comment distinguer science, métaphore et philosophie sur Flux Info ?','level'=>'Méthode','a'=>'La Charte éditoriale définit cinq registres : Fait Établi, Ordre de Grandeur, Hypothèse Discutée, Métaphore Pédagogique et Réflexion Philosophique. Cette classification est destinée à empêcher qu’une image ou une intuition soit prise pour un résultat scientifique.','src'=>[['Charte Éditoriale de Flux Info','politique-editoriale.php']]],
 ['q'=>'Comment soutenir le projet ?','level'=>'Information','a'=>'Le partage des contenus reste une forme de soutien essentielle. Une contribution financière facultative peut aussi aider à couvrir l’hébergement, les sauvegardes, la maintenance, la documentation des contenus et le développement des expériences interactives.','src'=>[['Nous Soutenir','gardien.php']]],
]
];
$faqSchema=[];
foreach($sections as $questions){foreach($questions as $item){$faqSchema[]=['@type'=>'Question','name'=>$item['q'],'acceptedAnswer'=>['@type'=>'Answer','text'=>$item['a']]];}}

ob_start();
include __DIR__ . '/header.php';
$headerOutput = ob_get_clean();
$headerParts = explode('<header class="archipel-header">', $headerOutput, 2);
$headerHead = $headerParts[0];
$headerNavigation = isset($headerParts[1]) ? '<header class="archipel-header">' . $headerParts[1] : $headerOutput;
?>
<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= htmlspecialchars($pageTitle,ENT_QUOTES,'UTF-8') ?></title>
<meta name="description" content="<?= htmlspecialchars($pageDesc,ENT_QUOTES,'UTF-8') ?>">
<?= $headerHead ?>
<script type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'FAQPage','@id'=>'https://flux-info.net/faq.php#faq','url'=>'https://flux-info.net/faq.php','inLanguage'=>'fr-FR','isPartOf'=>['@id'=>'https://flux-info.net/#website'],'mainEntityOfPage'=>['@id'=>'https://flux-info.net/faq.php#webpage'],'publisher'=>['@id'=>'https://flux-info.net/#organization'],'mainEntity'=>$faqSchema],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?></script>
<?php include_once __DIR__ . '/seo-head.php'; ?>
<style>
.faq-main{position:relative;z-index:4;max-width:980px;margin:0 auto;padding:68px 24px 110px;color:inherit}.faq-hero{text-align:center;max-width:820px;margin:0 auto 58px}.faq-hero h1{margin:0;font-size:clamp(2rem,5vw,3.7rem);font-weight:250}.faq-lead{margin:20px auto 0;line-height:1.75;opacity:.78}.faq-method{margin:24px auto 0;padding:16px 19px;border:1px solid color-mix(in srgb,currentColor 13%,transparent);border-radius:20px;background:color-mix(in srgb,currentColor 3%,transparent);font-size:.9rem;line-height:1.65}.faq-method a{color:inherit}.faq-section{margin-top:62px}.faq-section h2{margin:0 0 18px;padding-bottom:12px;border-bottom:1px solid color-mix(in srgb,currentColor 12%,transparent);font-size:1.45rem;font-weight:300}.faq-item{border-bottom:1px solid color-mix(in srgb,currentColor 8%,transparent)}.faq-item summary{cursor:pointer;list-style:none;display:flex;align-items:center;gap:12px;padding:23px 0;font-size:1.03rem;line-height:1.45}.faq-item summary::-webkit-details-marker{display:none}.faq-item summary::after{content:'+';margin-left:auto;font-size:1.25rem;opacity:.55}.faq-item[open] summary::after{content:'-'} .faq-proof{flex:0 0 auto;padding:5px 8px;border:1px solid color-mix(in srgb,currentColor 15%,transparent);border-radius:999px;font-size:.55rem;letter-spacing:.07em;text-transform:uppercase;opacity:.62}.faq-answer{padding:0 0 24px 0;max-width:840px}.faq-answer p{margin:0;line-height:1.75;opacity:.82}.faq-sources{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.faq-sources a{display:inline-flex;padding:7px 10px;border-radius:999px;border:1px solid color-mix(in srgb,currentColor 11%,transparent);color:inherit;text-decoration:none;font-size:.63rem;opacity:.7}.faq-sources a:hover,.faq-sources a:focus-visible{opacity:1}.faq-note{margin-top:58px;padding:20px;border-radius:22px;border:1px solid color-mix(in srgb,currentColor 12%,transparent);background:color-mix(in srgb,currentColor 3%,transparent);line-height:1.7;opacity:.8}body.reading-mode .faq-method,body.reading-mode .faq-note{background:color-mix(in srgb,currentColor 2%,transparent)}@media(max-width:650px){.faq-item summary{align-items:flex-start;flex-wrap:wrap}.faq-proof{order:2}.faq-item summary::after{position:absolute;right:24px}.faq-item summary{padding-right:32px}}
</style>
</head><body>
<?= $headerNavigation ?>
<main class="faq-main"><header class="faq-hero"><h1>Questions Fréquentes</h1><p class="faq-lead">Une FAQ pour comprendre les phénomènes, mais aussi pour savoir quel statut donner aux réponses. Lorsque la science est incertaine ou qu’une formule est volontairement imagée, nous le signalons.</p><p class="faq-method">Repères utilisés : <strong>Fait Établi</strong>, <strong>Ordre de Grandeur</strong>, <strong>Hypothèse Discutée</strong>, <strong>Métaphore Pédagogique</strong> et <strong>Réflexion Philosophique</strong>. <a href="politique-editoriale.php">Lire la Charte Éditoriale</a>.</p></header>
<?php $i=1; foreach($sections as $title=>$questions): ?><section class="faq-section"><h2><?= htmlspecialchars($title,ENT_QUOTES,'UTF-8') ?></h2><?php foreach($questions as $item): ?><details class="faq-item"><summary><span><?= $i++ ?>. <?= htmlspecialchars($item['q'],ENT_QUOTES,'UTF-8') ?></span><span class="faq-proof"><?= htmlspecialchars($item['level'],ENT_QUOTES,'UTF-8') ?></span></summary><div class="faq-answer"><p><?= htmlspecialchars($item['a'],ENT_QUOTES,'UTF-8') ?></p><?php if($item['src']): ?><div class="faq-sources"><?php foreach($item['src'] as [$label,$url]): ?><a href="<?= htmlspecialchars($url,ENT_QUOTES,'UTF-8') ?>"<?= str_starts_with($url,'http')?' target="_blank" rel="noopener noreferrer"':'' ?>>Source : <?= htmlspecialchars($label,ENT_QUOTES,'UTF-8') ?></a><?php endforeach; ?></div><?php endif; ?></div></details><?php endforeach; ?></section><?php endforeach; ?>
<div class="faq-note"><strong>Une source n’abolit pas la nuance.</strong> Une source institutionnelle ou académique peut établir un mécanisme ou un ordre de grandeur sans valider toutes les extrapolations narratives que l’on pourrait en tirer. C’est pourquoi Flux Info cherche à sourcer les faits et à nommer séparément les métaphores et réflexions.</div></main>
<?php if(file_exists('footer-archipel.php')) include 'footer-archipel.php'; ?>
</body></html>
